exp_id: exp000_default
seed: 42

competition:
  slug: playground-series-s6e6
  task_type: tabular_classification

data:
  train_path: data/raw/train.csv
  test_path: data/raw/test.csv
  sample_submission_path: data/raw/sample_submission.csv
  fold_path: data/folds/folds_v001.csv

features:
  sets:
    - basic

target:
  column: class

model:
  name: lightgbm
  params:
    learning_rate: 0.03
    n_estimators: 1000

training:
  n_folds: 5
  early_stopping_rounds: 100
  max_train_minutes: 20
  metric: balanced_accuracy

output:
  save_oof: true
  save_submission: true
  save_feature_importance: true
